name: Build and publish a Docker images

on:
  push:
    branches: ['master']
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    name: Build ${{ matrix.image }}:${{ matrix.version }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        image: 
          - php
          - php-fpm
          - php-testing
          - php-phpqa
        version:
          - 8.1
          - 8.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: ${{ matrix.image }}
          push: true
          build-args: PHP_VERSION=${{ matrix.version }}
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/${{ matrix.image }}:${{ matrix.version }}
          platforms: linux/arm64,linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
